### ISSUE TITLE
Issue uploading histogram to tensorboard.dev

### ISSUE THREAD

**Issue by jlperla** [PhilipVinc/TensorBoardLogger.jl#76]
On windows:
I follow the histogram example in https://github.com/PhilipVinc/TensorBoardLogger.jl/blob/master/examples/Histograms.jl
```julia
using TensorBoardLogger #import the TensorBoardLogger package
using Logging #import Logging package

logger = TBLogger("histogramlogs", tb_append) #create tensorboard logger

################log histogram example:################
#using logger interface
with_logger(logger) do
    for i in 1:100
        x0 = 0.5+i/30; s0 = 0.5/(i/20);
        edges = collect(-5:0.1:5)
        centers = collect(edges[1:end-1] .+0.05)
        histvals = [exp(-((c-x0)/s0)^2) for c = centers]
        data_tuple = (edges, histvals)
        @info "histogram/loggerinterface" autobin=rand(10).+0.1*i manualbin=data_tuple
    end
end
```
Running it in tensorboard on my computer, everything looks great.  i.e.
```
tensorboard --logdir histogramlogs
```
However, when I follow the instructions to upload it,
```bash
tensorboard dev upload --logdir \ 
     'histogramlogs'
```
It returns a link for tensorboard, but the output says
```
PermissionError: [WinError 5] Access is denied: '\\$Recycle.Bin\\S-1-5-18'
```
I tried running as an administrator and it didn't help, but the `\\$Recyle.Bin` is very suspicious.

The full output
```
S C:\Users\jlperla\Documents\GitHub\DifferentiableStateSpaceModels.jl> tensorboard dev upload --logdir \
TensorFlow installation not found - running with reduced feature set.
Data for the "graphs" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Data for the "histograms" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Data for the "hparams" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Upload started and will continue reading any new data as it's added
to the logdir. To stop uploading, press Ctrl-C.

View your TensorBoard live at: https://tensorboard.dev/experiment/QWseahp3Rfy8MKLWoiVtKg/


Done. View your TensorBoard at https://tensorboard.dev/experiment/QWseahp3Rfy8MKLWoiVtKg/
Traceback (most recent call last):
  File "c:\users\jlperla\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jlperla\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jlperla\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "c:\users\jlperla\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "c:\users\jlperla\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\program.py", line 290, in main
    return runner(self.flags) or 0
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\uploader\uploader_subcommand.py", line 633, in run
    return _run(flags)
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\uploader\uploader_subcommand.py", line 140, in _run
    intent.execute(server_info, channel)
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\uploader\uploader_subcommand.py", line 447, in execute
    uploader.start_uploading()
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\uploader\uploader.py", line 199, in start_uploading
    self._upload_once()
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\uploader\uploader.py", line 213, in _upload_once
    self._logdir_loader.synchronize_runs()
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\uploader\logdir_loader.py", line 70, in synchronize_runs
    for subdir in io_wrapper.GetLogdirSubdirectories(self._logdir):
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\backend\event_processing\io_wrapper.py", line 232, in <genexpr>
    subdir
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\backend\event_processing\io_wrapper.py", line 183, in ListRecursivelyViaWalking
    for dir_path, _, filenames in tf.io.gfile.walk(top, topdown=True):
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 719, in walk
    for subitem in walk(joined_subdir, topdown, onerror=onerror):
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 719, in walk
    for subitem in walk(joined_subdir, topdown, onerror=onerror):
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 696, in walk
    listing = listdir(top)
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 658, in listdir
    return get_filesystem(dirname).listdir(dirname)
  File "c:\users\jlperla\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 193, in listdir
    entries = os.listdir(compat.as_str_any(dirname))
PermissionError: [WinError 5] Access is denied: '\\$Recycle.Bin\\S-1-5-18'
```
Note the bottom,

**Comment by PhilipVinc** [comment]
A quick googling suggests that is an error that might be thrown when renaming files from Python...

I have to confess that I just found out about TensorboArd.dev! 
I think the issue is not really in TensorBoardLogger.jl itself but rather in TB failing because we encode some extra metadata compared to python's TB.

I'd like to bring this issue upstream, however could you please do the following:

 - can you check that a log file generated with TensorboardX in Python is successfully uploaded?
 - can you upload the Tensorboard log file that is failing?

**Comment by jlperla** [comment]
@sebastiangomez87   Can you try to replicate this error and try the things that @PhilipVinc  is suggesting?  I am curious if this fails on linux/WSL or is just a windows thing.

**Comment by PhilipVinc** [comment]
Locally I cannot reproduce your error, however, the online visualiser shows no data at all, even scalar...

**Comment by jlperla** [comment]
Maybe we should we try this without the pictures and with a trivial scalar?  Maybe I was wrong and the issue has nothing to do with histograms/images.

**Comment by PhilipVinc** [comment]
On my computer (Mac) scalars don't work either.

I think the issue is on the .proto file: I know that there is a tiny difference somewhere between a .proto generated by TensorFlow and the one generated by TensorBoardLogger, however, I have never been able to track down it's origin, and locally everything always worked so I stopped thinking about it.

It's possible that this is causing problems in this context.

That's why I'm interested in knowing if with tensorboardx (which is a python code very similar to tensorboardlogger) the same problem appears...

**Comment by jlperla** [comment]
@PhilipVinc  Can you tell us exactly what TensorBoardX code you want us to run to isolate the problem?

**Comment by PhilipVinc** [comment]
The example here should be ok https://github.com/lanpa/tensorboardX

**Comment by PhilipVinc** [comment]
Hmm, no wait. I have no idea what I did before but now everything works
(i have v2.3.0 of tensorboard)
```
•5% ➜ tensorboard dev upload --logdir \
    'histogramlogs/'

Data for the "graphs" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Data for the "histograms" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Data for the "hparams" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line argument.
Upload started and will continue reading any new data as it's added
to the logdir. To stop uploading, press Ctrl-C.

View your TensorBoard live at: https://tensorboard.dev/experiment/v2qKNr9OS4SwLzXhEmAjkQ/

[2020-09-24T22:05:52] Uploader started.
[2020-09-24T22:05:52] Total uploaded: 0 scalars, 200 tensors (131.7 kB), 0 binary objects
```

**Comment by jlperla** [comment]
I did the following code:
```python
import matplotlib.pyplot as plt
from tensorboardX import SummaryWriter

plt.switch_backend('agg')

fig = plt.figure()

c1 = plt.Circle((0.2, 0.5), 0.2, color='r')
c2 = plt.Circle((0.8, 0.5), 0.2, color='r')

ax = plt.gca()
ax.add_patch(c1)
ax.add_patch(c2)
plt.axis('scaled')


from tensorboardX import SummaryWriter
writer = SummaryWriter()
writer.add_figure('matplotlib', fig)
writer.close()
```
then
```bash
tensorboard --logdir runs
```
and it looked good in the browser.

Then I closed tensorboard, and ran
```bash
tensorboard --logdir 'runs'
```
... and...  it said it worked and uploaded, but it didn't seem to have anything at the link.

**Comment by PhilipVinc** [comment]
Ok, so I strongly believe you have a problem with your tensor board installation...
what version do you have?

**Comment by jlperla** [comment]
Gotcha.
```
tensorboard                        2.3.0
tensorboard-plugin-wit             1.7.0
tensorboardX                       2.1
```
Python/conda/pip is the worst for reproducibility.  What I wouldn't give for a Package.toml/Manifest.toml approach there.
@sebastiangomez87 can try this on his (newly installed) conda and if he doesn't have any problems, lets assume this is not your problem :-)

**Comment by PhilipVinc** [comment]
if you manage to let it work could you please let me know? I'd like to be 100% sure it's not our issue...

**Comment by sebastiangomez87** [comment]
I'm having the same issues. I tried both of @jlperla codes in Julia and Python, and I also tried the example demo_custom_scalar in Python.

**Comment by jlperla** [comment]
@PhilipVinc   I still think this is an error in tensorboardlogger and Windows.  There may be other things going on as well, but the error message we are all getting that `PermissionError: [WinError 5] Access is denied: '\\$Recycle.Bin\\S-1-5-18'` suggests something very windows specific.

Maybe moving or deleting files or something like that? Do you have a windows machine or virtual machine you could try it on?

**Comment by jlperla** [comment]
For whatever reason, things are now working better on some other machines.   No idea.  So I am going to close this.
